name: "Push manifest"

inputs:
  manifest-repository:
    description: "Manifest repository name"
    required: true
  manifest-base-branch:
    description: "Manifest base branch name"
    required: true
  image-tag:
    description: "Container image tag"
    required: true
  overlays-path:
    description: "Kustomization overlay path"
    requried: true
  create-pr:
    description: "Flag to determine creating PR"
    required: true
  github-personal-access-token:
    description: "GitHub Personal Access Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.manifest-repository }}
        ref: ${{ inputs.manifest-base-branch }}
        path: manifests
        token: ${{ inputs.github-personal-access-token }}
        fetch-depth: 0
    - name: change k8s manifest
      uses: mikefarah/yq@v4.5.1
      with:
        cmd: |
          yq eval '(.images.[] | select(.name == "sample")).newTag="${{ inputs.image-tag }}"' -i manifests/${{ inputs.overlays-path }}/kustomization.yaml
    - name: commit manifest
      working-directory: manifests
      run: |
        set -ex
        echo ${{ inputs.create-pr }}
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add ${{ inputs.overlays-path }}/kustomization.yaml
        git commit -m "Update manifest"
      shell: bash
    - name: push manifest to main
      if: "${{ inputs.create-pr }}" == 'false'
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.manifest-base-branch }}
        directory: manifests
        github_token: ${{ inputs.github-personal-access-token }}
        repository: ${{ inputs.manifest-repository }}
    - name: push manifest to release tag
      if: "${{ inputs.create-pr }}" == 'true'
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.image-tag }}
        directory: manifests
        github_token: ${{ inputs.github-personal-access-token }}
        repository: ${{ inputs.manifest-repository }}
    - name: create pull request
      if: "${{ inputs.create-pr }}" == 'true'
      working-directory: manifests
      env:
        GH_TOKEN: ${{ inputs.github-personal-access-token }}
      run: gh pr create -B main -H ${{ inputs.image-tag }} -t "Test PR" -b ""
      shell: bash
