name: "Build the image"
description: ""
inputs:
  contiainer-args:
    description: "Args to build the image"
    required: true
  manifest-repository:
    description: "Manifest repository name"
    required: true

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/Dockerfile
          push: true
          tags: kawa1/github-actions-test:latest
      - name: Print args
        run: echo "Hello! ${{ inputs.container-args }} and ${{ inputs.manifest-repository }}"
