name: "Build the image"

inputs:
  manifests-repository:
    required: true
  dockerhub-username:
    required: true
  dockerhub-token:
    required: true
  how-to-build:
    required: true

outputs:
  image-tag:
    value: ${{ steps.build-info.outputs.image-tag }}

runs:
  using: "composite"
  steps:
    - name: container-build-args
      run: |

        CURRENT_TAG=""
        INPUT_TYPE=$(echo "${{ github.ref }}" | awk -F '/' '{print $2}')
        
        if [ "${INPUT_TYPE}" = "tags" ];then
          CURRENT_TAG=$(git describe --tags --abbrev=0 --match 'v*')
        else
          CURRENT_TAG="${{ github.event.inputs.environment }}"
        fi
          
        echo ${CURRENT_TAG}
        echo 'CURRENT_TAG='${CURRENT_TAG} >> $GITHUB_ENV
      shell: bash
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set image tag
      id: set-image-tag
      run: | 
        SHORT_SHA=$(git rev-parse --short HEAD)
        IMAGE_TAG="${{ env.CURRENT_TAG}}-${SHORT_SHA}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> ${GITHUB_ENV}
      shell: bash
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - name: Build and push using docker
      if: inputs.how-to-build == "docker"
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        push: true
        tags: kawa1/github-actions-test:${{ env.IMAGE_TAG }}
    - name: Build and push using bazel
      if: inputs.how-to-build == "bazel"
      run: |
        bazel build "//:image-push"
      shell: bash
    - name: build info
      id: build-info
      run: | 
        echo "image-tag=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
      shell: bash
