name: "Build the image"

on:
  workflow_call:
    inputs:
      contiainer-args:
        required: true
        type: string
      manifests-repository:
        required: true
        type: string
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
outputs:
  image-tag:
    description: "Image tag"
    value: ${{ steps.build-info.outputs.image-tag }}

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: kawa1/github-actions-test:${{ inputs.container-args.CURRENT_TAG}}
      - name: build info
        id: build-info
        run: | 
          echo "image-tag=$(echo ${IMAGE_TAG})" >> $GITHUB_OUTPUT
        shell: bash
      - name: Print args
        run: echo "Hello! ${{ inputs.container-args }} and ${{ inputs.manifest-repository }}"
