name: "build and deploy"
run-name: "Branch: ${{ github.ref_name }} Env: ${{ inputs.environment }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to build the container image"
        required: true
        type: choice
        options:
          - staging
          - production
      create-pr-in-manifest-repository:
        description: "Create Pull Request in manifest repository"
        required: true
        type: boolean
        default: false

env:
  MANIFEST_REPO: tkkawa/twitter-manifests

jobs:
  set-metadata:
    name: set metadata
    runs-on: ubuntu-latest
    outputs:
      container-args: ${{ steps.container-build-args.outputs.CONTAINER_BUILD_ARGS }}
    steps:
      - uses: actions/checkout@v4
      - name: container-build-args
        run: |

          INPUT_TYPE=$(echo "${{ github.ref }}" | awk -F '/' '{print $2}')
          CURRENT_TAG=""
          if [ "${INPUT_TYPE}" = "tags"] ;then
            CURRENT_TAG="${{ github.event.inputs.environment }}"
          else
            CURRENT_TAG=$(git describe --tags --abbrev=0 --match 'v*')
          if 
            
          echo ${CURRENT_TAG}

          echo 'CONTAINER_BUILD_ARGS<<'${EOF} >> $GITHUB_OUTPUT
          echo 'CURRENT_TAG='${CURRENT_TAG} >> $GITHUB_OUTPUT
          echo ${EOF} >> $GITHUB_OUTPUT
      - name: print log
        run: echo "Hello! ${{ github.event.inputs.environment }}"
            