name: "build and deploy"
run-name: "Branch: ${{ github.ref_name }} Env: ${{ inputs.environment }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to build the container image"
        required: true
        type: choice
        options:
          - staging
          - production
      create-pr-in-manifest-repository:
        description: "Create Pull Request in manifest repository"
        required: true
        type: boolean
        default: false
      how-to-build:
        description: "Choose how to build an image"
        required: true
        type: choice
        options:
          - docker
          - bazel

env:
  MANIFEST_REPO: tkkawa/test-app

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: build image
        id: build-image
        uses: ./.github/actions/build_image
        with:
          manifests-repository: tkkawa/twitter-manifests
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          how-to-build: ${{ inputs.how-to-build }}
      - name: change manifest
        id: change-manifest
        uses: ./.github/actions/push_manifest
        with:
          manifest-repository: ${{ env.MANIFEST_REPO }}
          manifest-base-branch: main
          image-tag: ${{ steps.build-image.outputs.image-tag }}
          overlays-path: "sample/overlays/staging"
          create-pr: ${{ inputs.create-pr-in-manifest-repository }}
          github-personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # run: echo "Create PR! ${{ steps.build-image.outputs.image-tag }}" 

            