name: "build and deploy"
run-name: "Branch: ${{ github.ref_name }} Env: ${{ inputs.environment }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to build the container image"
        required: true
        type: choice
        options:
          - staging
          - production
      create-pr-in-manifest-repository:
        description: "Create Pull Request in manifest repository"
        required: true
        type: boolean
        default: false

env:
  MANIFEST_REPO: tkkawa/twitter-manifests

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: build image
        id: build-image
        uses: ./.github/actions/build_image
        with:
          manifests-repository: tkkawa/twitter-manifests
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create_pr
        run: echo "Create PR! ${{ steps.build-image.outputs.image-tag }}" 
            