name: "Go test"
on:
  pull_request

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - name: Format code
        id: format
        run: |
          # gofmt -l .
          # OUTPUT=$(gofmt -l .)
          # echo "$OUTPUT"
          # echo "::set-output name=result::$OUTPUT"
          GOFILES=$(gofmt -l .)
          echo $(GOFILES)
          echo 'GOFILES='${GOFILES} >> $GITHUB_ENV
        shell: bash
      - name: Comment to PR
        if: steps.format.outputs.GOFILES != ''
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const output = "## Format failed\n<summary>files: ${{ steps.format.outputs.GOFILES }}</summary>";

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

