name: "Go test"
on:
  pull_request

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - name: Format code
        run: gofmt -l .
