name: "Go test"
on:
  pull_request

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - name: Format code
        run: |
          GOFILES=$(gofmt -l .)
          echo 'GOFILES='$(GOFILES) >> $GITHUB_ENV
        shell: bash
      - name: Comment to PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo ${env.GOFILES} > /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
        shell: bash

